/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as V1GameRouteImport } from './routes/v1/game'
import { Route as V2GameRouteImport } from './routes/v2/game'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1GameRoute = V1GameRouteImport.update({
  id: '/v1/game',
  path: '/v1/game',
  getParentRoute: () => rootRouteImport,
} as any)
const V2GameRoute = V2GameRouteImport.update({
  id: '/v2/game',
  path: '/v2/game',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/v1/game': typeof V1GameRoute
  '/v2/game': typeof V2GameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/v1/game': typeof V1GameRoute
  '/v2/game': typeof V2GameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/v1/game': typeof V1GameRoute
  '/v2/game': typeof V2GameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/v1/game' | '/v2/game'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/v1/game' | '/v2/game'
  id: '__root__' | '/' | '/v1/game' | '/v2/game'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  V1GameRoute: typeof V1GameRoute
  V2GameRoute: typeof V2GameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/game': {
      id: '/v1/game'
      path: '/v1/game'
      fullPath: '/v1/game'
      preLoaderRoute: typeof V1GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2/game': {
      id: '/v2/game'
      path: '/v2/game'
      fullPath: '/v2/game'
      preLoaderRoute: typeof V2GameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  V1GameRoute: V1GameRoute,
  V2GameRoute: V2GameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
